<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>true</Prefer32Bit>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>SageBridgeConnector</AssemblyName>
    <RootNamespace>SageBridge.Connector</RootNamespace>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Microsoft.AspNet.WebApi.Owin" Version="5.2.9" />
      <PackageReference Include="Microsoft.Owin.Host.HttpListener" Version="4.2.2" />
      <PackageReference Include="Microsoft.Owin.Hosting" Version="4.2.2" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="System.Data.SQLite.Core" Version="1.0.118.0" />
      <PackageReference Include="System.Net.Http" Version="4.3.4" />
      <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
      <PackageReference Include="Serilog" Version="3.1.1" />
      <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
      <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Sage_SA.SDK">
      <HintPath>C:\Program Files (x86)\Sage 50 Accounting SDK\SDK\Sage_SA.SDK.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Sage_SA.Domain">
      <HintPath>C:\Program Files (x86)\Sage 50 Accounting SDK\SDK\Sage_SA.Domain.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Sage_SA.Domain.Utility">
      <HintPath>C:\Program Files (x86)\Sage 50 Accounting SDK\SDK\Sage_SA.Domain.Utility.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Update="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="C:\Program Files (x86)\Sage 50 Accounting SDK\SDK\*.dll"
          Exclude="C:\Program Files (x86)\Sage 50 Accounting SDK\SDK\Newtonsoft.Json.dll">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="C:\Program Files (x86)\Sage 50 Accounting SDK\SDK\fr\*.dll">
      <Link>fr\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="C:\Program Files (x86)\Sage 50 Accounting SDK\SDK\CloudID\*.dll">
      <Link>CloudID\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
